### ISSUE TITLE
Can't customize due to internal protection

### ISSUE THREAD

**Issue by LucasAdam** [liufengting/FTPopOverMenu_Swift#1]
Hey, 

I'm trying to use your pod (as a framework) in my app but I can't access the shared configuration properties. I've looked down your files but I can't see any internal protected class... Any idea ? 

<img width="651" alt="capture d ecran 2017-01-05 a 11 25 54" src="https://cloud.githubusercontent.com/assets/9447241/21677294/dae8ebba-d339-11e6-9cc0-03f791f8ed1d.png">

**Comment by liufengting** [comment]
I will fix this today. Or you can add public to each variables for now.

**Comment by liufengting** [comment]
Bug Fixed. Use version 0.0.6.

**Comment by ir-fuel** [comment]
Is it possible the podspec was not updated?
