### ISSUE TITLE
rightbarbuttonitem弹出后点击leftbarbutton出错

### ISSUE THREAD

**Issue by LeiStoneLi** [liufengting/FTPopOverMenu_Swift#15]
rightbarbuttonitem弹出后点击leftbarbutton，不退出当前页面，反而相当于点击了弹出中设置的第一个选项

**Comment by liufengting** [comment]
rightbarbuttonitem弹出后leftbarbutton, 此时接收的动作是使menu消失，而不是leftbarbutton的动作。
