### ISSUE TITLE
How do I set the text color of the menu items?

### ISSUE THREAD

**Issue by Sweeper777** [liufengting/FTPopOverMenu_Swift#20]
In an old version of this pod (0.0.7), there was a property called `textColor` in `FTConfiguration`. This does not seem to be present in the version I am currently using (0.1.2). How can I set the text color?

**Comment by ganeshnic24** [comment]
How do I set the text color of the menu items? 
using swift 4.2

**Comment by liufengting** [comment]
@ganeshnic24 please run the demo
