### ISSUE TITLE
希望能有 SPM 的支持

### ISSUE THREAD

**Issue by legolasW** [liufengting/FTPopOverMenu_Swift#35]
如题，谢谢作者！

**Comment by liufengting** [comment]
<img width="671" alt="image" src="https://user-images.githubusercontent.com/4414522/82154321-95e11680-989f-11ea-9ace-957ccf2addd4.png">
好像是支持的

**Comment by liufengting** [comment]
包名好像是FTPopOverMenu，不是FTPopOverMenu_Swift

**Comment by legolasW** [comment]
谢谢！！
