### ISSUE TITLE
FTCellConfiguration not working.

### ISSUE THREAD

**Issue by KuldeepAIP** [liufengting/FTPopOverMenu_Swift#37]
I want to change text color and font. For that i have tried below code but it's not working.

```
let cellConfiguration = FTCellConfiguration()
cellConfiguration.textColor = .black
cellConfiguration.textFont = UIFont.init(name: Fonts.AvenirRegular, size: 14.0)!
cellConfiguration.textAlignment = .left
        
var cellConfigurationArray: [FTCellConfiguration]?
cellConfigurationArray?.append(cellConfiguration)
        
FTPopOverMenu.showForSender(sender: sender, with: activeEmployeeOption, menuImageArray: [], cellConfigurationArray: cellConfigurationArray, done: { (selectedIndex) -> () in
    print(selectedIndex)
})
```

No crash with above code but color & font not working.

**OR**

```
FTPopOverMenu.showForSender(sender: sender, with: activeEmployeeOption, menuImageArray: [], cellConfigurationArray: [cellConfiguration], done: { (selectedIndex) -> () in
     print(selectedIndex)
})
```
If i use above line of code then app getting crash with Fatal error. 

**Fatal error: Index out of range: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-1103.2.25.8/swift/stdlib/public/core/ContiguousArrayBuffer.swift, line 444**

Will anyone please guide me why it's not working or let me know the steps to change it.
Thanks

**Comment by liufengting** [comment]
try this

<img width="763" alt="image" src="https://user-images.githubusercontent.com/4414522/90465050-23533180-e141-11ea-8efa-13e73f1f9284.png">

**Comment by KuldeepAIP** [comment]
@liufengting , thanks for you comment. i am using **pod 'FTPopOverMenu_Swift', '~> 0.2.0'** and getting error with below line.

`let configuration = FTConfiguration()`

**'FTConfiguration' initializer is inaccessible due to 'internal' protection level**
