### ISSUE TITLE
Package.swift: invalid custom path 'FTPopOverMenu_Swift' for target 'FTPopOverMenu_Swift'

### ISSUE THREAD

**Issue by Rj707** [liufengting/FTPopOverMenu_Swift#40]
/Users/userName/Library/Developer/Xcode/DerivedData/projectName/SourcePackages/checkouts/FTPopOverMenu_Swift/Package.swift: **invalid custom path 'FTPopOverMenu_Swift' for target 'FTPopOverMenu_Swift'**

**Comment by liufengting** [comment]
@Rj707 Please try v0.4.2
